version: '3.4'

services:
  nats:
    image: nats-streaming:0.25.2
    entrypoint:
      - /nats-streaming-server
      - -cid
      - crypto-cluster
    ports:
      - "4222:4222"
      - "8222:8222"
    restart: always
    tty: true

  marketdepth.pub:
    image: ${DOCKER_REGISTRY-}pub
    build:
      context: .
      dockerfile: src/MarketDepth.Pub/Dockerfile
    env_file:
      - .env
    depends_on:
      - nats

  marketdepth.wss:
    image: ${DOCKER_REGISTRY-}wss
    build:
      context: .
      dockerfile: src/MarketDepth.Sub.WsServer/Dockerfile
    expose:
      - "5050"
    ports:
      - "5050:5050"
    env_file:
      - .env
    depends_on:
      - nats